export const SELECTORES = {
  TABLA_ZONA: '#tablaCoordinadoresDL',
  TABLA_SECCIONALES: '#tablaCoordinadoresSeccional',
  TABLA_COMITES: '#tablaDatosComite',
  TABLA_VOLUNTARIOS: '#tablaVoluntarios',
  TABLA_PROMOTORES: '#tablaDatosPromotor',
  TABLA_PROMOVIDOS: '#tablaPromovidos',
  TABLA_COORDINADORES_DL: '#tablaCoordinadoresDL',
  TABLA_COORDINADORES_COTS: '#tablaCoordinadoresCots',
  TABLA_COORDINADORES_MUNICIPAL: '#tablaCoordinadoresMunicipal',
  ICONO_USUARIOS: '.fa-users',
  ICONO_LAPIZ: '.fa-pencil',
  BOTON_ICONO_USUARIOS: 'button > i.fa-users',
  BOTON_VOLVER_SECCIONAL: '#botonVolverSeccional',
  BOTON_VOLVER_COMITE: '#botonVolverComite',
  BOTON_VOLVER_PROMOTOR: '#botonVolverPromotor',
  BOTON_VOLVER_PROMOVIDOS: '#botonVolverPromovido',
  BOTON_AGREGAR_PROMOVIDO: '#botonAgregarPromovido',
  BOTON_GUARDAR_GENERAL: '#botonGuardarGeneral',
  MODAL_CAPTURA_PROMOVIDO: '#modalCapturaGeneral',
  SPINNER: '#ajaxBusy',
  TXT_NOMBRE: "#txtNombre",
  TXT_PATERNO: "#txtPaternoCoordinador",
  TXT_MATERNO: "#txtMaternoCoordinador",
  TXT_SECCIONAL: "#txtSeccionalCoordinador",
  TXT_COLONIA: "#txtColoniaCoordinador", 
  TXT_CP: "#txtCPCoordinador", 
  TXT_CALLE: "#txtCalleCoordinador", 
  TXT_NUMERO: "#txtNumeroCoordinador", 
  TXT_CLAVE: "#txtClaveElectorCoordinador", 
  TXT_CELULAR: "#txtCelularCoordinador"
}